- name: Disable Swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Remove SWAP from fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
  - swap
  - none

- name: Reduce Swappiness
  ansible.posix.sysctl:
    name: vm.swappiness
    value: '0'
    state: present

- name: Install required packages
  apt:
    name:
    - curl
    - ca-certificates
    state: present
    update_cache: yes

- name: Download k3s installation script
  get_url:
    url: https://get.k3s.io
    dest: /tmp/k3s_install.sh
    mode: '0755'

- name: Install k3s
  command: /tmp/k3s_install.sh
  args:
    creates: /usr/local/bin/k3s

- name: Wait for k3s to start
  wait_for:
    path: /etc/rancher/k3s/k3s.yaml
    state: present
    delay: 10
    timeout: 300

- name: Copy k3s.yaml to user's home directory
  copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "{{ ansible_env.HOME }}/.kube/config"
    remote_src: yes
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'

- name: Create kubectl symlink
  file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/kubectl
    state: link

- name: Get nodes
  command: k3s kubectl get nodes
  register: get_nodes
  changed_when: false

- name: Display nodes
  debug:
    var: get_nodes.stdout_lines
