- name: Remove the first line
  ansible.builtin.shell: "sed -i '1d' /etc/apt/sources.list"
  become: yes

- name: Install CLI Tools
  ansible.builtin.apt:
    update_cache: yes
    pkg:
    - ca-certificates
    - curl

- name: Install Kubectl
  become: yes
  shell: |
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/arm64/kubectl"
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
    rm kubectl
  args:
    creates: "/usr/local/bin/kubectl"
